#Stanford residency yaml input file

gurobi:
  Threads: 2

scheduling:
  service_requirements: data/service.csv
  ap1_residents: data/ap1.csv
  ap2_residents: data/ap2.csv

output:
  file: data/schedule.csv

rules:
  - upper_bound:
      service: "Vacation"
      count: 3
  - single_block:
      service: "NEURO"
  - upper_bound:
      service: "NEURO"
  - single_block:
      service: "AUTOPSY"
      who: "AP1"
  - upper_bound:
      service: "AUTOPSY"
  #- single_block:
  #    service: "HEME"
  #- single_block:
  #    service: "SP_PED_ST"
  - do_before:
      service: "Gross bootcamp"
      week: 7
  - do_after:
      service: "SP_PED_ST"
      week: 24
      who: "AP1"
  - in_blocks:
      service: "VA"
      block_size: 2
  - upper_bound:
      service: "VA"
      count: 12
  - in_blocks:
      service: "DERM"
      block_size: 2
  - in_blocks:
      service: "FORENSICS"
      block_size: 2
  - sequence:
      first: "SP_FS"
      second: "Breast"

